#==================================================
# COURSE:		CSC 460, Lab4
# PROGRAMMER:		Noah Bumgardner (nb)
# LAST MODIFIED DATE:	2015-08-31
# DESCRIPTION:		This make file is for hw3_v5.cpp
#			 and its dependencies.
# FILE:			makefile
#==================================================

generate: hw3_v5.cpp
  c++11 hw3_v5.cpp -o generate
