#==================================================
# COURSE:				CSC460, hw3
# PROGRAMMERS:			Ali Bajwa (ab)
#						Noah Bumgardner (nb)
# LAST MODIFIED DATE:	2015-10-09
# DESCRIPTION:		This make file is for hw3.cpp
#			 	and its dependencies.
# FILE:			makefile
#==================================================

generate: hw3.cpp
	c++11 hw3.cpp -o generate
