#=====================================================
# COURSE:				CSC460, hw6
# PROGRAMMERS:			Ali Bajwa (ab)
#						Noah Bumgardner (nb)
# LAST MODIFIED DATE:	2015-12-2
# DESCRIPTION:			This make file is for hw6.cpp
#					 	 and its dependencies.
# FILE:					makefile
#=====================================================

generate: scheduler.cpp
	c++11 scheduler.cpp -o scheduler
	c++11 generator.cpp -o generator
	
clean:
	scheduler generator
